#!/usr/bin/env python
# -*- coding: utf-8 -*-

import pytest

from simulariumio.springsalad import SpringsaladConverter, SpringsaladData


@pytest.mark.parametrize(
    "trajectory, expected_data",
    [
        # truncated data from tutorial example
        (
            SpringsaladData(
                path_to_sim_view_txt=(
                    "simulariumio/tests/data/springsalad/"
                    "Simulation0_SIM_VIEW_Run0.txt"
                ),
                scale_factor=0.1,
            ),
            {
                "trajectoryInfo": {
                    "version": 2,
                    "timeUnits": {
                        "magnitude": 1.0,
                        "name": "s",
                    },
                    "timeStepSize": 0.1,
                    "totalSteps": 2,
                    "spatialUnits": {
                        "magnitude": 10.0,
                        "name": "nm",
                    },
                    "size": {"x": 5.0, "y": 5.0, "z": 10.0},
                    "cameraDefault": {
                        "position": {"x": 0, "y": 0, "z": 120},
                        "lookAtPosition": {"x": 0, "y": 0, "z": 0},
                        "upVector": {"x": 0, "y": 1, "z": 0},
                        "fovDegrees": 50.0,
                    },
                    "typeMapping": {
                        "0": {"name": "GREEN"},
                        "1": {"name": "RED"},
                        "2": {"name": "GRAY"},
                        "3": {"name": "CYAN"},
                        "4": {"name": "BLUE"},
                    },
                },
                "spatialData": {
                    "version": 1,
                    "msgType": 1,
                    "bundleStart": 0,
                    "bundleSize": 2,
                    "bundleData": [
                        {
                            "frameNumber": 0,
                            "time": 0.0,
                            "data": [
                                1000.0,
                                100000000.0,
                                0.0,
                                -2.3515194000000004,
                                4.1677663,
                                -0.2872943,
                                0.0,
                                0.0,
                                0.0,
                                0.2,
                                0.0,
                                1000.0,
                                100010000.0,
                                0.0,
                                -1.1726563,
                                3.7363461000000004,
                                -0.47181300000000004,
                                0.0,
                                0.0,
                                0.0,
                                0.2,
                                0.0,
                                1000.0,
                                100200001.0,
                                1.0,
                                -0.3749313,
                                0.6674895000000001,
                                -0.5000000,
                                0.0,
                                0.0,
                                0.0,
                                0.2,
                                0.0,
                                1000.0,
                                100200000.0,
                                2.0,
                                -0.3749313,
                                0.6674895000000001,
                                0.000000,
                                0.0,
                                0.0,
                                0.0,
                                0.2,
                                0.0,
                                1000.0,
                                100200002.0,
                                3.0,
                                -0.3749313,
                                0.6674895000000001,
                                0.5000000,
                                0.0,
                                0.0,
                                0.0,
                                0.2,
                                0.0,
                                1000.0,
                                100300000.0,
                                4.0,
                                -2.9673074,
                                0.5123882000000001,
                                5.0633669,
                                0.0,
                                0.0,
                                0.0,
                                0.1,
                                0.0,
                            ],
                        },
                        {
                            "frameNumber": 1,
                            "time": 0.10000000998802996,
                            "data": [
                                1000.0,
                                100200001.0,
                                1.0,
                                3.8385084999999997,
                                -2.5307899000000003,
                                -0.5000000,
                                0.0,
                                0.0,
                                0.0,
                                0.2,
                                0.0,
                                1000.0,
                                100200000.0,
                                2.0,
                                3.7610036000000004,
                                -2.4899603,
                                0.000000,
                                0.0,
                                0.0,
                                0.0,
                                0.2,
                                0.0,
                                1000.0,
                                100200002.0,
                                3.0,
                                3.6784268,
                                -2.5100304,
                                0.5000000,
                                0.0,
                                0.0,
                                0.0,
                                0.2,
                                0.0,
                                1000.0,
                                100210001.0,
                                1.0,
                                0.9422604,
                                1.1849763,
                                -0.5000000,
                                0.0,
                                0.0,
                                0.0,
                                0.2,
                                0.0,
                                1000.0,
                                100300000.0,
                                4.0,
                                1.7784686,
                                0.8480382000000001,
                                1.8389947,
                                0.0,
                                0.0,
                                0.0,
                                0.1,
                                0.0,
                            ],
                        },
                    ],
                },
                "plotData": {"version": 1, "data": []},
            },
        ),
    ],
)
def test_springsalad_converter(trajectory, expected_data):
    converter = SpringsaladConverter(trajectory)
    buffer_data = converter._read_trajectory_data(converter._data)
    assert expected_data == buffer_data
    assert converter._check_agent_ids_are_unique_per_frame(buffer_data)
