name: Create Issue

on:
  issues:
    types: [opened]
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@a9f041ddd462ed185893ea1024cec954f50dbe42
        with:
          project-url: https://github.com/orgs/simularium/projects/5
          github-token: ${{ secrets.SIMULARIUM }}
