name: Install Conda Deps

on:
  workflow_call:
      inputs:
        runs-on:
          required: false
          type: string
          default: "ubuntu-latest"       
        python-version:
          required: false
          type: string
          default: "3.9"


jobs:
  install:
    runs-on: ${{ input.runs-on }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup MiniConda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ input.python-version }}
          channels: conda-forge 
      - name: Install Conda Deps
        shell: bash -l {0}
        run: |
          conda install readdy==2.0.9
          conda install numpy
